version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    reviewers:
      - "whispr-team"  
    assignees:
      - "glopez-dev"   # Remplacez par votre nom d'utilisateur
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    # Grouper les mises à jour mineures et patches ensemble
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
        update-types:
          - "minor"
          - "patch"
      types:
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Ignorer certaines dépendances si nécessaire
    ignore:
      # Exemple: ignorer les mises à jour majeures pour certains packages critiques
      - dependency-name: "typeorm"
        update-types: ["version-update:semver-major"]
      - dependency-name: "grpc-tools"
        update-types: ["version-update:semver-major"]
    # Permettre les mises à jour de vulnérabilités même si ignorées
    allow:
      - dependency-type: "all"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"

  # Enable version updates for Docker (si vous avez un Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker"
    labels:
      - "docker"
      - "dependencies"
