name: Docker Build & Deploy

on:
  repository_dispatch:
    types: [run-docker]
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      should_deploy:
        required: false
        type: string
        default: 'false'

permissions:
  contents: read
  packages: write
  id-token: write  # For GitHub attestations
  attestations: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ================================
  # Build and test Docker image
  # ================================
  docker-build:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tags: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.event.client_payload.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=auth-service-test
            type=raw,value=auth-service-{{date 'YYYYMMDD'}}-{{sha}}

      - name: Build Docker image for testing
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: auth-service:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          echo "🧪 Testing Docker image..."
          
          # Start image in background
          docker run -d --name test-container -p 3001:3001 \
            -e NODE_ENV=test \
            auth-service:test
          
          # Wait for service to be ready
          echo "⏳ Waiting for service to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:3001/health; then
              echo "✅ Health check passed"
              break
            fi
            echo "Attempt $i/30 failed, retrying..."
            sleep 2
          done
          
          # Basic tests
          echo "🔍 Running basic endpoint tests..."
          curl -f http://localhost:3001/health || exit 1
          
          # Cleanup
          docker stop test-container
          docker rm test-container
          
          echo "✅ Docker image tests passed"

      - name: Run Trivy on Docker image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'auth-service:test'
          format: 'sarif'
          output: 'docker-trivy-results.sarif'
        continue-on-error: true

      - name: Upload Docker Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('docker-trivy-results.sarif') != ''
        with:
          sarif_file: 'docker-trivy-results.sarif'

      - name: Should deploy check
        id: deploy-check
        run: |
          SHOULD_DEPLOY="${{ inputs.should_deploy || github.event.client_payload.should_deploy }}"
          echo "should_deploy=$SHOULD_DEPLOY" >> $GITHUB_OUTPUT
          echo "🔍 Should deploy: $SHOULD_DEPLOY"

  # ================================
  # Push Docker image (conditional)
  # ================================
  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    needs: docker-build
    if: (inputs.should_deploy == 'true') || (github.event.client_payload.should_deploy == 'true')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.event.client_payload.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for production
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate SBOM with attestation
        uses: anchore/sbom-action@v0.16.0
        id: sbom
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: spdx-json
          output-file: sbom.spdx.json
          dependency-snapshot: true

      - name: Attest SBOM to image
        uses: actions/attest-sbom@v1
        id: attest-sbom
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          sbom-path: sbom.spdx.json
          push-to-registry: true

      - name: Generate provenance attestation
        uses: actions/attest-build-provenance@v1
        id: attest-provenance
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Upload SBOM artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom.spdx.json
          retention-days: 30